language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 8.2
    - 8.3
    - 8.4

before-install:
  - composer self-update

install:
    - composer update

script:
    - php ./vendor/bin/phpunit
