language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.4
    - 8.0
    - 8.1
    - 8.2

before-install:
  - composer self-update

install:
    - composer update

script:
    - php ./vendor/bin/phpunit
